export const lipsticks = [
  {
    'level': 1,
    'color': '#D62352',
    'id': '49',
    'name': '撩骚',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#DC4B41',
    'id': '14',
    'name': '一见倾心',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#B22146',
    'id': '05',
    'name': '浮生若梦',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#A25356',
    'id': '08',
    'name': '纯真梦幻',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#DF3443',
    'id': '12',
    'name': '红粉派对',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#E06C68',
    'id': '15',
    'name': '珊瑚恋人',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#842C71',
    'id': '19',
    'name': '华丽转身',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#D13C4F',
    'id': '43',
    'name': '唇印',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#B71D32',
    'id': '04',
    'name': '危情禁果',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#DE2361',
    'id': '06',
    'name': '情窦初开',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#B05856',
    'id': '09',
    'name': '裸色暗恋',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#E06F70',
    'id': '13',
    'name': '邂逅巴黎',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#CD4143',
    'id': '16',
    'name': '糖果女孩',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#EC6A70',
    'id': '41',
    'name': '告白',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#EFE9DE',
    'id': '42',
    'name': '初恋',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#C60F2F',
    'id': '45',
    'name': '拥吻',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#BB6868',
    'id': '47',
    'name': '心跳',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#E0186B',
    'id': '50',
    'name': '约定',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#D45E85',
    'id': '52',
    'name': '游戏',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#C16E6F',
    'id': '44',
    'name': '意外',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#D1121B',
    'id': '46',
    'name': '钟情',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#8E243E',
    'id': '48',
    'name': '夜色',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  },
  {
    'level': 1,
    'color': '#EE7486',
    'id': '51',
    'name': '私语',
    'brand': '圣罗兰',
    'series': '莹亮纯魅唇膏',
    'price': 10,
    'priceUnit': 0,
    'produce': 1,
    'produceUnit': 0,
  }
];
