export const Resources = [
  ['background', 'res/image/home/background.png'],
  ['nickname', 'res/image/home/nickname.png'],
  ['userCoins', 'res/image/home/coins.png'],
  ['recycleButton', 'res/image/home/recycle.png'],
  ['shopButton', 'res/image/home/shop.png'],
  ['stage', 'res/image/home/stage.png'],
  ['coin', 'res/image/home/icon_coin.png'],
  ['coinDisplay', 'res/image/shop/icon_coinshow.png'],
  ['exit', 'res/image/shop/icon_exit.png'],
  ['heart', 'res/image/shop/icon_heart.png'],
  ['price', 'res/image/shop/icon_price.png'],
  ['goods', 'res/image/shop/lipstick_list.png'],
  ['box', 'res/image/shop/lipstick_show.png'],
  ['shopBackground', 'res/image/shop/shop_bg.png'],
  ['lipstick', 'res/image/lipstick.png'],
];
